### ISSUE TITLE
NoSuchMethodError: The method 'removeFragment' was called on null

### ISSUE THREAD

**Issue by Abouassi98** [nyartech/hyperpay#5] opened 2021-11-06 14:02 UTC
[HyperpayPlugin/getCheckoutID] NoSuchMethodError: The method 'removeFragment' was called on null.
                               Receiver: null
                               Tried calling: removeFragment()

**Comment by Abouassi98** [comment] 2021-11-06 14:10
![image](https://user-images.githubusercontent.com/53384802/140612628-0a773c5d-9dd2-49ee-9326-952c5474eaa9.png)

**Comment by pr-Mais** [comment] 2021-11-06 14:53
Please remove `http://` from `_host`, a host shouldn't contain a scheme, it's already defined in `_scheme`

**Comment by Abouassi98** [comment] 2021-11-06 15:04
I have tried that but give me a new issue

D/HyperpayPlugin(15942): Hyperpay service is connected, start listening...
[HyperpayPlugin/getCheckoutID] HttpException: 400: 
                               ddddd

**Comment by Abouassi98** [comment] 2021-11-06 15:04
![image](https://user-images.githubusercontent.com/53384802/140614246-3cbf1a74-3eaf-4677-bf3a-ddb971450bc0.png)

**Comment by Abouassi98** [comment] 2021-11-06 15:33
my API run on postman but must add token  
![image](https://user-images.githubusercontent.com/53384802/140615039-f74713d9-900e-420a-ae3c-19f2879cce3a.png)
how I pass the token in the URI object ??
![image](https://user-images.githubusercontent.com/53384802/140615072-be8cf47a-4fa0-4b2d-9380-12793f7d8549.png)
Is that correct ?!

**Comment by pr-Mais** [comment] 2021-11-06 15:42
No. The headers are not queryParameters, add them to `CheckoutSetting` object, there's a property that takes your headers.

**Comment by pr-Mais** [comment] 2021-11-06 15:43
Please remove all the screenshots you added, you are exposing all the live credentials and API keys of your app in a public repo.

**Comment by Abouassi98** [comment] 2021-11-06 15:45
ok thanks ,but i have new issue 
![image](https://user-images.githubusercontent.com/53384802/140615477-252d7a8a-e2b0-4685-b641-d11d0f74d59c.png)
[HyperpayPlugin/getCheckoutID] Bad state: Cannot set the body fields of a Request with content-type "application/json".

**Comment by Abouassi98** [comment] 2021-11-06 15:50
if I have removed  'Content-Type'  i have new issue as 

[HyperpayPlugin/getCheckoutID] NoSuchMethodError: The method '[]' was called on null.
                               Receiver: null
                               Tried calling: []("code")

**Comment by pr-Mais** [comment] 2021-11-06 16:04
I see the issue. The body of the request should be json encoded because you're sending the request with json as content-type. I will push an update shortly.

**Comment by pr-Mais** [comment] 2021-11-06 16:11
Please update your pub spec with following, temporarily, wanna check if this will solve your issue before releasing an update:

```yaml
dependencies:
  hyperpay:
    git:
      url: https://github.com/nyartech/hyperpay.git
```

**Comment by Abouassi98** [comment] 2021-11-06 16:25
Sorry but I have the same issue also

**Comment by pr-Mais** [comment] 2021-11-06 16:28
```bash
rm pubspec.lock
flutter pub get
```

**Comment by Abouassi98** [comment] 2021-11-06 16:28
![image](https://user-images.githubusercontent.com/53384802/140616787-5dc9cfdf-517a-4142-a31e-7626e200aaa8.png)

**Comment by pr-Mais** [comment] 2021-11-06 16:31
what doesn't your endpoint return? The code is assuming it's a Map that has the key `result.code`, can you show me the result when running the TEST checkoutID endpoint?

**Comment by Abouassi98** [comment] 2021-11-06 16:32
![image](https://user-images.githubusercontent.com/53384802/140616881-d663f71a-2659-4a41-babf-1bbd1fa7a090.png)

**Comment by pr-Mais** [comment] 2021-11-06 16:34
Yeah here's the problem. Can you remove the key "API" and return the "result"? this is what the plugin expects `_resBody['result']['code']`, I will let it throw an exception so it's clear what the problem is, thank you for reporting!

**Comment by pr-Mais** [comment] 2021-11-06 16:47
Run pub get, it should throw now if the result isn't structured as expected. Please lmk of any other issues you're having.

**Comment by Abouassi98** [comment] 2021-11-06 16:47
Ok , thanks a lot 
 Now i will edit response and  try again

**Comment by pr-Mais** [comment] 2021-11-06 16:50
Will be waiting your response

**Comment by Abouassi98** [comment] 2021-11-06 17:09
this exception show to me before editing response : 
[HyperpayPlugin/getCheckoutID] "RESPONSE BODY NOT IDENTIFIED: The returned result does not containt the key "result" as the first key., details: please structure the returned body as {result: {code: CODE, description: DESCRIPTION}, id: CHECKOUT_ID, ...}."


but after editing the response  it works correctly  

thanks  a lot

**Comment by pr-Mais** [comment] 2021-11-06 17:12
You performed a whole test transaction with no issues? check your HyperPay dashboard as well and make sure the transaction looks exactly as expected.
Additionally, please lmk if it works in production as expected before closing this issue.

Thanks to you for reporting and helping in improving the plugin!

**Comment by Abouassi98** [comment] 2021-11-06 17:32
Thanks for your helping , everything is okay

**Closed** 2021-11-06 17:35 UTC
Labels: bug
